import storageAdapter from './storageAdapter';

const activeRuns = new Map();

function pad(value) {
  return String(value).padStart(2, '0');
}

function getDateKey(date) {
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
}

function dateFromKey(value) {
  const [year, month, day] = value.split('-').map(Number);
  return new Date(year, month - 1, day);
}

function getAccountStartDate(user, records) {
  if (user?.createdAt) return getDateKey(new Date(user.createdAt));
  const firstRecord = records.map((record) => record.date).filter(Boolean).sort()[0];
  return firstRecord || getDateKey(new Date());
}

export function processMissedAttendanceDays(userId, today = new Date()) {
  if (!userId) return Promise.resolve({ processedDates: [] });
  if (activeRuns.has(userId)) return activeRuns.get(userId);

  const run = processMissedAttendanceDaysForUser(userId, today).finally(() => activeRuns.delete(userId));
  activeRuns.set(userId, run);
  return run;
}

async function processMissedAttendanceDaysForUser(userId, today) {

  const [user, storedAttendance, storedLeaveRequests] = await Promise.all([
    storageAdapter.getUserByUserId(userId),
    storageAdapter.getAttendanceForUser(userId),
    storageAdapter.getLeaveRequestsForUser(userId),
  ]);
  const attendance = Array.isArray(storedAttendance) ? storedAttendance : [];
  const leaveRequests = Array.isArray(storedLeaveRequests) ? storedLeaveRequests : [];
  const attendanceByDate = new Map(attendance.map((record) => [record.date, record]));
  const leaveCoversDate = (dateKey) => leaveRequests.some((request) => (
    request?.fromDate
    && request?.toDate
    && !['absence', 'missed-day-leave'].includes(request.autoGenerated)
    && request.fromDate <= dateKey
    && request.toDate >= dateKey
  ));
  const generatedLeaveByDate = new Map(
    leaveRequests
      .filter((request) => ['absence', 'missed-day-leave'].includes(request?.autoGenerated))
      .map((request) => [request.fromDate, request]),
  );
  const endDate = dateFromKey(getDateKey(today));
  endDate.setDate(endDate.getDate() - 1);
  const startDate = dateFromKey(getAccountStartDate(user, attendance));
  const processedDates = [];

  for (const date = startDate; date <= endDate; date.setDate(date.getDate() + 1)) {
    const dateKey = getDateKey(date);
    const existing = attendanceByDate.get(dateKey);
    if (existing?.checkIn) continue;
    if (leaveCoversDate(dateKey)) {
      const remainingRequests = leaveRequests.filter((request) => !(
        ['absence', 'missed-day-leave'].includes(request?.autoGenerated)
        && request.fromDate === dateKey
      ));
      if (remainingRequests.length !== leaveRequests.length) {
        leaveRequests.splice(0, leaveRequests.length, ...remainingRequests);
        processedDates.push(dateKey);
      }
      if (existing && (existing.status !== 'Leave' || existing.absent === true)) {
        existing.status = 'Leave';
        existing.absent = false;
        if (!processedDates.includes(dateKey)) processedDates.push(dateKey);
      }
      continue;
    }

    const existingGeneratedLeave = generatedLeaveByDate.get(dateKey);
    const needsAttendanceUpdate = !existing || existing.status !== 'Leave' || existing.absent === true;
    const needsLeaveUpdate = !existingGeneratedLeave || existingGeneratedLeave.autoGenerated !== 'missed-day-leave' || existingGeneratedLeave.leaveType !== 'Leave';
    if (!needsAttendanceUpdate && !needsLeaveUpdate) continue;

    if (existing) {
      existing.status = 'Leave';
      existing.absent = false;
    } else {
      const leaveRecord = { date: dateKey, status: 'Leave', absent: false };
      attendance.push(leaveRecord);
      attendanceByDate.set(dateKey, leaveRecord);
    }

    if (needsLeaveUpdate) {
      const generatedLeave = {
        ...(existingGeneratedLeave || {}),
        id: existingGeneratedLeave?.id || `leave-${dateKey}`,
        fromDate: dateKey,
        toDate: dateKey,
        leaveType: 'Leave',
        reason: 'Automatically recorded: no punch-in or submitted leave request',
        autoGenerated: 'missed-day-leave',
        createdAt: existingGeneratedLeave?.createdAt || `${dateKey}T23:59:59.000Z`,
      };
      if (existingGeneratedLeave) {
        const index = leaveRequests.indexOf(existingGeneratedLeave);
        leaveRequests[index] = generatedLeave;
      } else {
        leaveRequests.push(generatedLeave);
      }
      generatedLeaveByDate.set(dateKey, generatedLeave);
    }
    processedDates.push(dateKey);
  }

  if (processedDates.length) {
    await Promise.all([
      storageAdapter.saveAttendanceForUser(userId, attendance),
      storageAdapter.saveLeaveRequestsForUser(userId, leaveRequests),
    ]);
  }

  return { processedDates };
}