jest.mock('../src/services/storageAdapter', () => ({
  __esModule: true,
  default: {
    getUserByUserId: jest.fn(),
    getAttendanceForUser: jest.fn(),
    getLeaveRequestsForUser: jest.fn(),
  },
}));

import storageAdapter from '../src/services/storageAdapter';
import { calculateMonthlyAttendanceMetrics, getMonthKey, getMonthlyAttendanceMetrics } from '../src/services/attendanceMetricsService';

describe('calculateMonthlyAttendanceMetrics', () => {
  test('formats the current month key from the local calendar date', () => {
    expect(getMonthKey(new Date(2026, 8, 26))).toBe('2026-09');
  });

  test('uses calendar month length and counts each punched date once', () => {
    const metrics = calculateMonthlyAttendanceMetrics({
      month: '2026-01',
      attendance: [
        { date: '2026-01-02', checkIn: '09:00' },
        { date: '2026-01-02', checkIn: '09:15', checkOut: '17:00' },
        { date: '2026-01-03', checkIn: '08:55' },
      ],
      accountStartDate: '2026-01-01',
      today: new Date(2026, 0, 4),
    });

    expect(metrics).toMatchObject({ nod: 31, attended: 2, leave: 0, percentage: 6 });
  });

  test('shows 20 percent for six punched days in a 30-day month', () => {
    const attendance = Array.from({ length: 6 }, (_, index) => ({
      date: `2026-09-${String(index + 1).padStart(2, '0')}`,
      checkIn: '09:00',
    }));
    const metrics = calculateMonthlyAttendanceMetrics({
      month: '2026-09',
      attendance,
      today: new Date(2026, 8, 27),
    });

    expect(metrics).toMatchObject({ nod: 30, attended: 6, percentage: 20 });
  });

  test('handles leap-year February and excludes dates covered by leave', () => {
    const metrics = calculateMonthlyAttendanceMetrics({
      month: '2024-02',
      attendance: [{ date: '2024-02-01', checkIn: '09:00' }],
      leaveRequests: [{ fromDate: '2024-02-02', toDate: '2024-02-03', leaveType: 'Medical Leave' }],
      accountStartDate: '2024-02-01',
      today: new Date(2024, 2, 1),
    });

    expect(metrics).toMatchObject({ nod: 29, attended: 1, leave: 2, percentage: 3 });
  });

  test('counts legacy absent attendance and generated entries as Leave', () => {
    const metrics = calculateMonthlyAttendanceMetrics({
      month: '2026-09',
      attendance: [{ date: '2026-09-25', status: 'Absent', absent: true }],
      leaveRequests: [{ fromDate: '2026-09-24', toDate: '2026-09-24', autoGenerated: 'absence' }],
      accountStartDate: '2026-09-24',
      today: new Date(2026, 8, 26),
    });

    expect(metrics).toMatchObject({ nod: 30, attended: 0, leave: 2 });
  });

  test('counts an explicit Leave record for today', () => {
    const metrics = calculateMonthlyAttendanceMetrics({
      month: '2026-09',
      attendance: [
        { date: '2026-09-26', status: 'Absent', absent: true },
      ],
      accountStartDate: '2026-09-26',
      today: new Date(2026, 8, 26),
    });

    expect(metrics.leave).toBe(1);
  });

  test('counts past and upcoming leave days in the selected month once per date', () => {
    const metrics = calculateMonthlyAttendanceMetrics({
      month: '2026-09',
      leaveRequests: [
        { fromDate: '2026-09-25', toDate: '2026-09-27', leaveType: 'Casual Leave' },
        { fromDate: '2026-09-27', toDate: '2026-10-02', leaveType: 'Medical Leave' },
        { fromDate: '2026-09-28', toDate: '2026-09-28', autoGenerated: 'absence' },
      ],
      accountStartDate: '2026-09-01',
      today: new Date(2026, 8, 27),
    });

    expect(metrics.leave).toBe(6);
  });

  test('recalculates from updated leave records when metrics are loaded again', async () => {
    storageAdapter.getUserByUserId.mockResolvedValue({ createdAt: '2026-09-24T10:00:00.000Z' });
    storageAdapter.getAttendanceForUser.mockResolvedValue([]);
    storageAdapter.getLeaveRequestsForUser
      .mockResolvedValueOnce([])
      .mockResolvedValueOnce([{ fromDate: '2026-09-24', toDate: '2026-09-25' }]);

    const today = new Date(2026, 8, 26);
    const beforeLeaveUpdate = await getMonthlyAttendanceMetrics('employee-1', '2026-09', today);
    const afterLeaveUpdate = await getMonthlyAttendanceMetrics('employee-1', '2026-09', today);

    expect(beforeLeaveUpdate.leave).toBe(0);
    expect(afterLeaveUpdate.leave).toBe(2);
  });
});