jest.mock('../src/services/storageAdapter', () => ({
  __esModule: true,
  default: {
    getUserByUserId: jest.fn(),
    getAttendanceForUser: jest.fn(),
    saveAttendanceForUser: jest.fn(),
    getLeaveRequestsForUser: jest.fn(),
    saveLeaveRequestsForUser: jest.fn(),
  },
}));

import storageAdapter from '../src/services/storageAdapter';
import { processMissedAttendanceDays } from '../src/services/attendanceAbsenceService';
import { getLeaveStatus } from '../src/services/leaveService';

describe('processMissedAttendanceDays', () => {
  beforeEach(() => jest.clearAllMocks());

  test('marks missed days as Leave once and mirrors them into the leave summary', async () => {
    const attendance = [{ date: '2026-09-24', checkIn: '09:00' }];
    let leaveRequests = [];
    storageAdapter.getUserByUserId.mockResolvedValue({ createdAt: '2026-09-24T12:00:00.000Z' });
    storageAdapter.getAttendanceForUser.mockImplementation(async () => attendance);
    storageAdapter.getLeaveRequestsForUser.mockImplementation(async () => leaveRequests);
    storageAdapter.saveAttendanceForUser.mockImplementation(async (userId, records) => {
      attendance.splice(0, attendance.length, ...records);
    });
    storageAdapter.saveLeaveRequestsForUser.mockImplementation(async (userId, requests) => {
      leaveRequests = requests;
    });

    const today = new Date(2026, 8, 27, 12);
    const firstRun = await processMissedAttendanceDays('employee-1', today);
    await processMissedAttendanceDays('employee-1', today);

    expect(firstRun.processedDates).toEqual(['2026-09-25', '2026-09-26']);
    expect(attendance).toContainEqual({ date: '2026-09-25', status: 'Leave', absent: false });
    expect(attendance).toContainEqual({ date: '2026-09-26', status: 'Leave', absent: false });
    expect(leaveRequests.filter((request) => request.autoGenerated === 'missed-day-leave')).toHaveLength(2);
    expect(leaveRequests.map((request) => request.id)).toEqual(['leave-2026-09-25', 'leave-2026-09-26']);
    expect(leaveRequests.every((request) => getLeaveStatus(request, today) === 'Completed')).toBe(true);
    expect(storageAdapter.saveAttendanceForUser).toHaveBeenCalledTimes(1);
    expect(storageAdapter.saveLeaveRequestsForUser).toHaveBeenCalledTimes(1);
  });

  test('does not auto-generate Leave for a date covered by a submitted request', async () => {
    const attendance = [];
    let leaveRequests = [{
      id: 'request-1',
      fromDate: '2026-09-25',
      toDate: '2026-09-25',
      leaveType: 'Casual Leave',
    }];
    storageAdapter.getUserByUserId.mockResolvedValue({ createdAt: '2026-09-25T08:00:00.000Z' });
    storageAdapter.getAttendanceForUser.mockImplementation(async () => attendance);
    storageAdapter.getLeaveRequestsForUser.mockImplementation(async () => leaveRequests);
    storageAdapter.saveAttendanceForUser.mockImplementation(async (userId, records) => {
      attendance.splice(0, attendance.length, ...records);
    });
    storageAdapter.saveLeaveRequestsForUser.mockImplementation(async (userId, requests) => {
      leaveRequests = requests;
    });

    await processMissedAttendanceDays('employee-2', new Date(2026, 8, 26, 12));

    expect(attendance).toEqual([]);
    expect(leaveRequests).toHaveLength(1);
    expect(storageAdapter.saveAttendanceForUser).not.toHaveBeenCalled();
  });

  test('migrates a stored legacy Absent record to Leave', async () => {
    const attendance = [{ date: '2026-09-25', status: 'Absent', absent: true }];
    let leaveRequests = [{
      id: 'absence-2026-09-25',
      fromDate: '2026-09-25',
      toDate: '2026-09-25',
      leaveType: 'Absent',
      autoGenerated: 'absence',
      createdAt: '2026-09-25T23:59:59.000Z',
    }];
    storageAdapter.getUserByUserId.mockResolvedValue({ createdAt: '2026-09-25T08:00:00.000Z' });
    storageAdapter.getAttendanceForUser.mockResolvedValue(attendance);
    storageAdapter.getLeaveRequestsForUser.mockResolvedValue(leaveRequests);
    storageAdapter.saveAttendanceForUser.mockImplementation(async (userId, records) => {
      attendance.splice(0, attendance.length, ...records);
    });
    storageAdapter.saveLeaveRequestsForUser.mockImplementation(async (userId, requests) => {
      leaveRequests = requests;
    });

    await processMissedAttendanceDays('employee-3', new Date(2026, 8, 26, 12));

    expect(attendance[0]).toMatchObject({ status: 'Leave', absent: false });
    expect(leaveRequests).toHaveLength(1);
    expect(leaveRequests[0]).toMatchObject({ id: 'absence-2026-09-25', leaveType: 'Leave', autoGenerated: 'missed-day-leave' });
  });

  test('removes generated Leave when a submitted request covers the same date', async () => {
    const attendance = [{ date: '2026-09-25', status: 'Leave', absent: false }];
    let leaveRequests = [
      { id: 'request-1', fromDate: '2026-09-25', toDate: '2026-09-25', leaveType: 'Casual Leave' },
      { id: 'leave-2026-09-25', fromDate: '2026-09-25', toDate: '2026-09-25', leaveType: 'Leave', autoGenerated: 'missed-day-leave' },
    ];
    storageAdapter.getUserByUserId.mockResolvedValue({ createdAt: '2026-09-25T08:00:00.000Z' });
    storageAdapter.getAttendanceForUser.mockResolvedValue(attendance);
    storageAdapter.getLeaveRequestsForUser.mockResolvedValue(leaveRequests);
    storageAdapter.saveAttendanceForUser.mockResolvedValue();
    storageAdapter.saveLeaveRequestsForUser.mockImplementation(async (userId, requests) => {
      leaveRequests = requests;
    });

    await processMissedAttendanceDays('employee-4', new Date(2026, 8, 26, 12));

    expect(leaveRequests).toHaveLength(1);
    expect(leaveRequests[0].id).toBe('request-1');
    expect(storageAdapter.saveLeaveRequestsForUser).toHaveBeenCalledTimes(1);
  });
});